# NumPy

In [2]:
import numpy as np

zero_vector = np.zeros(5)
zero_vector

array([0., 0., 0., 0., 0.])

In [3]:
zero_matrix = np.zeros((5,3)) # tuple(row,column)
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
y = np.array([3,4,5])
y

array([3, 4, 5])

In [12]:
Z = np.array([[1,2,3],[4,5,6],[7,8,9]])
Z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
Z.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
z

array([5, 7, 9])

In [30]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[7,8,9],[4,5,3]])

X[:,1]

array([2, 5])

In [31]:
X[:,1] + Y[:,1]

array([10, 10])

In [34]:
X[1,:]

array([4, 5, 6])

In [35]:
X[1,:]+Y[1,:]

array([ 8, 10,  9])

In [36]:
X[0]

array([1, 2, 3])

In [41]:
X[1][1]

5

##  Indexing NumPy Arrays

In [44]:
z1 = np.array([2,4,7,3,5])
z2 = z1 + 2
z2

array([4, 6, 9, 5, 7])

2 is added to all the elements of z1.

In [45]:
index = [0,2,3]
z2[index]

array([4, 9, 5])

here index list is working as index.

In [48]:
z2 < 5

array([ True, False, False, False, False])

This boolan array also can be used for indexing.

In [49]:
z2[z2 < 5]

array([4])

As one element in z2 is greater than 5.

## Slice

In [61]:
z = np.array([1,2,3,4,5,6,7,8,9])

x = z[:3]
x

array([1, 2, 3])

In [52]:
x[1] = 10
x

array([ 1, 10,  3])

In [53]:
z

array([ 1, 10,  3,  4,  5,  6,  7,  8,  9])

Both array is modified.

In [55]:
z = np.array([1,2,3,4,5,6,7,8,9])
index = np.array([0,1,2])
index

array([0, 1, 2])

In [56]:
x = z[index]
x

array([1, 2, 3])

In [58]:
x[1] = 10
x

array([ 1, 10,  3])

In [59]:
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Now it is not modified.

##  Examining NumPy Arrays

Linearly spaced array.

In [63]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

Logarithmically spaced array.

In [65]:
np.logspace(1,2,10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

Logarithmically spaced array. from log base 10 250 to log base 10 500

In [66]:
np.logspace(np.log10(250),np.log10(500),10)

array([250.        , 270.01493472, 291.63225989, 314.98026247,
       340.19750004, 367.43362307, 396.85026299, 428.62199143,
       462.93735614, 500.        ])

## shape

In [67]:
X = np.array([[1,2,3],[4,5,6]])
X.shape

(2, 3)

In [68]:
X.size

6

## ANY and ALL

In [70]:
np.random.random(10)

array([0.33563448, 0.94878954, 0.06992299, 0.49409158, 0.78391501,
       0.12188365, 0.40579509, 0.48600552, 0.62781229, 0.03916599])

In [76]:
x = np.random.random(10)

np.any(x > 0.9) # checking any of the element in x is greater than 0.9

True

In [77]:
x 

array([0.35030382, 0.27025038, 0.44353857, 0.20034079, 0.61889042,
       0.44318089, 0.93148737, 0.95140204, 0.87268019, 0.24878118])

In [78]:
np.all(x > 0.9) # checking all of the element in x is greater than 0.9

False

In [79]:
x

array([0.35030382, 0.27025038, 0.44353857, 0.20034079, 0.61889042,
       0.44318089, 0.93148737, 0.95140204, 0.87268019, 0.24878118])

In [80]:
np.all(x > 0.1)

True